import {
  Badge,
  Box,
  Button,
  Grid,
  Heading,
  Img,
  Input,
} from "@chakra-ui/react";
import { JsonMetadata, Nft, Option } from "@metaplex-foundation/js";
import {
  WalletDisconnectButton,
  WalletMultiButton,
} from "@solana/wallet-adapter-react-ui";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import useNFTs, { NftWithVerifiedName } from "../hooks/useNFTs";

const Home: NextPage = () => {
  const { nfts, getAllNftAccounts, signName } = useNFTs();

  const [selected, setSelected] = useState<NftWithVerifiedName>();
  const [editedName, setEditedName] = useState("");

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box py="20" px={10}>
        <Box
          display={"flex"}
          justifyContent="space-between"
          alignItems={"center"}
          gap="5"
        >
          <Button
            w="100%"
            h={50}
            mx={10}
            colorScheme={"purple"}
            onClick={getAllNftAccounts}
          >
            Get NFTs
          </Button>
          <WalletMultiButton />
          <WalletDisconnectButton />
        </Box>
        <Heading size={"lg"} textAlign="center">
          {selected?.name ?? selected?.json?.name}
          {selected?.verified && (
            <Badge colorScheme={"green"} ml="2">
              verified
            </Badge>
          )}
        </Heading>
        <Box mt={30} display={"flex"}>
          <Input
            maxW={"75%"}
            onChange={(e) => setEditedName(e.target.value)}
          ></Input>
          <Button
            ml={3}
            p={2}
            colorScheme="teal"
            onClick={() =>
              signName(editedName, selected?.mintAddress?.toString())
            }
          >
            change name
          </Button>
        </Box>
        <Grid py={10} templateColumns="1fr 1fr 1fr">
          {nfts.map((n, index) => {
            return (
              <Box key={index}>
                <Img
                  onClick={() => {
                    console.log("setting nft", n);
                    setSelected(n);
                  }}
                  src={n?.json?.image}
                  height="auto"
                ></Img>
              </Box>
            );
          })}
        </Grid>
      </Box>
    </>
  );
};

export default Home;
